export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const FETCH_REQUEST = 'data/people/REQUEST';
export const FETCH_SUCCESS = 'data/people/SUCCESS';
export const FETCH_FAILURE = 'data/people/FAILURE';

export const FETCH_REQUEST_HOMEWORLD = 'data/homeworld/REQUEST';
export const FETCH_SUCCESS_HOMEWORLD = 'data/homeworld/SUCCESS';
export const FETCH_FAILURE_HOMEWORLD= 'data/homeworld/FAILURE';

export const FETCH_REQUEST_FILMS = 'data/films/REQUEST';
export const FETCH_SUCCESS_FILMS = 'data/films/SUCCESS';
export const FETCH_FAILURE_FILMS= 'data/films/FAILURE';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const ADD_TO_FAVORITES_ERROR = 'ADD_TO_FAVORITES_ERROR';

export const  REMOVE_FROM_FAVORITES_SUCCESS = 'REMOVE_FROM_FAVORITES_SUCCESS';
export const REMOVE_FROM_FAVORITES_ERROR = 'REMOVE_FROM_FAVORITES_ERROR';

export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_ERROR = 'FETCH_FAVORITES_ERROR';
export const FETCH_REQUEST_FAVORITES = 'FETCH_REQUEST_FAVORITES';







